<script lang="ts">
	interface DraftVersion {
		id: string;
		content: string;
		timestamp: number;
		type: 'initial' | 'generated' | 'refined' | 'manual';
		description: string;
		wordCount: number;
	}

	export let versions: DraftVersion[] = [];
	export let onRestoreVersion: (version: DraftVersion) => void = () => {};
	export let onDeleteVersion: (versionId: string) => void = () => {};

	let showHistory = false;
	let selectedVersionIds: Set<string> = new Set();
	let compareMode = false;

	function addVersion(content: string, type: DraftVersion['type'], description: string) {
		const newVersion: DraftVersion = {
			id: `v${Date.now()}`,
			content,
			timestamp: Date.now(),
			type,
			description,
			wordCount: content.trim().split(/\s+/).filter(w => w.length > 0).length
		};
		versions = [...versions, newVersion];
	}

	function formatDate(timestamp: number): string {
		const date = new Date(timestamp);
		return date.toLocaleString();
	}

	function formatTime(timestamp: number): string {
		const date = new Date(timestamp);
		return date.toLocaleTimeString();
	}

	function getTypeColor(type: string): string {
		const colors = {
			initial: 'bg-blue-100 text-blue-800',
			generated: 'bg-purple-100 text-purple-800',
			refined: 'bg-amber-100 text-amber-800',
			manual: 'bg-gray-100 text-gray-800'
		};
		return colors[type as keyof typeof colors] || 'bg-gray-100 text-gray-800';
	}

	function getTypeLabel(type: string): string {
		const labels = {
			initial: '📝 Initial',
			generated: '✨ Generated',
			refined: '🔧 Refined',
			manual: '✏️ Manual'
		};
		return labels[type as keyof typeof labels] || type;
	}

	function toggleVersionSelection(versionId: string) {
		if (selectedVersionIds.has(versionId)) {
			selectedVersionIds.delete(versionId);
		} else {
			selectedVersionIds.add(versionId);
		}
		selectedVersionIds = selectedVersionIds;
	}

	function enterCompareMode() {
		if (selectedVersionIds.size >= 2) {
			compareMode = true;
		}
	}

	function exitCompareMode() {
		compareMode = false;
	}

	function getHighlightedDiff(text1: string, text2: string): { text: string; isAdded: boolean }[] {
		// Simple word-level diff
		const words1 = text1.split(/\s+/);
		const words2 = text2.split(/\s+/);
		const result: { text: string; isAdded: boolean }[] = [];

		const maxLen = Math.max(words1.length, words2.length);
		for (let i = 0; i < maxLen; i++) {
			if (i < words1.length && i < words2.length) {
				if (words1[i] === words2[i]) {
					result.push({ text: words1[i], isAdded: false });
				} else {
					if (words1[i]) result.push({ text: words1[i], isAdded: false });
					if (words2[i]) result.push({ text: words2[i], isAdded: true });
				}
			} else if (i >= words1.length && words2[i]) {
				result.push({ text: words2[i], isAdded: true });
			} else if (i >= words2.length && words1[i]) {
				result.push({ text: words1[i], isAdded: false });
			}
		}
		return result;
	}

	$: selectedVersions = Array.from(selectedVersionIds)
		.map(id => versions.find(v => v.id === id))
		.filter(Boolean) as DraftVersion[];

	function exportVersion(version: DraftVersion) {
		const element = document.createElement('a');
		const file = new Blob([version.content], { type: 'text/markdown' });
		element.href = URL.createObjectURL(file);
		element.download = `draft_${formatDate(version.timestamp).replace(/[\s/:]/g, '_')}.md`;
		document.body.appendChild(element);
		element.click();
		document.body.removeChild(element);
	}

	export function trackGeneration(content: string, agent: string) {
		addVersion(content, 'generated', `Generated by ${agent}`);
	}

	export function trackRefinement(content: string, refinementType: string) {
		addVersion(content, 'refined', `Refined: ${refinementType}`);
	}

	export function trackManualEdit(content: string) {
		if (versions.length === 0) {
			addVersion(content, 'initial', 'Initial draft');
		} else {
			addVersion(content, 'manual', 'Manual edit');
		}
	}
</script>

<div class="space-y-4">
	<!-- Version History Header -->
	<div class="flex justify-between items-center">
		<button
			type="button"
			on:click={() => (showHistory = !showHistory)}
			class={`px-4 py-2 rounded-lg font-medium text-sm transition ${
				showHistory
					? 'bg-indigo-100 text-indigo-700'
					: 'bg-gray-100 text-gray-700 hover:bg-gray-200'
			}`}
		>
			📋 Version History ({versions.length})
		</button>

		{#if selectedVersionIds.size >= 2 && !compareMode}
			<button
				type="button"
				on:click={enterCompareMode}
				class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium text-sm transition"
			>
				🔍 Compare {selectedVersionIds.size} Versions
			</button>
		{/if}

		{#if compareMode}
			<button
				type="button"
				on:click={exitCompareMode}
				class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 font-medium text-sm transition"
			>
				Close Comparison
			</button>
		{/if}
	</div>

	{#if showHistory}
		<div class="bg-white border border-gray-200 rounded-lg p-4 space-y-3">
			{#if versions.length === 0}
				<p class="text-sm text-gray-500 text-center py-4">No versions yet. Generations and edits will appear here.</p>
			{:else if !compareMode}
				<!-- Version List -->
				<div class="space-y-2 max-h-96 overflow-y-auto">
					{#each [...versions].reverse() as version (version.id)}
						<div class="border border-gray-200 rounded-lg p-3 hover:bg-gray-50 transition">
							<div class="flex items-start justify-between gap-3">
								<div class="flex items-start gap-3 flex-1">
									<input
										type="checkbox"
										checked={selectedVersionIds.has(version.id)}
										on:change={() => toggleVersionSelection(version.id)}
										class="mt-1 w-4 h-4 rounded accent-indigo-600"
									/>
									<div class="flex-1">
										<div class="flex items-center gap-2">
											<span class={`px-2 py-1 rounded text-xs font-medium ${getTypeColor(version.type)}`}>
												{getTypeLabel(version.type)}
											</span>
											<span class="text-sm font-medium text-gray-900">{version.description}</span>
										</div>
										<div class="text-xs text-gray-500 mt-1">
											{formatDate(version.timestamp)} • {version.wordCount} words
										</div>
										<p class="text-xs text-gray-700 mt-2 line-clamp-2">
											{version.content.substring(0, 100)}...
										</p>
									</div>
								</div>

								<div class="flex gap-1">
									<button
										type="button"
										on:click={() => onRestoreVersion(version)}
										title="Restore this version"
										class="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-200 rounded transition"
									>
										↩️
									</button>
									<button
										type="button"
										on:click={() => exportVersion(version)}
										title="Download as markdown"
										class="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-200 rounded transition"
									>
										⬇️
									</button>
									<button
										type="button"
										on:click={() => onDeleteVersion(version.id)}
										title="Delete version"
										class="p-2 text-red-600 hover:text-red-900 hover:bg-red-100 rounded transition"
									>
										🗑️
									</button>
								</div>
							</div>
						</div>
					{/each}
				</div>
			{:else}
				<!-- Comparison View -->
				<div class="space-y-4">
					<h4 class="font-semibold text-gray-900">Comparing {selectedVersions.length} Versions</h4>

					{#if selectedVersions.length === 2}
						<div class="grid grid-cols-2 gap-4">
							{#each selectedVersions as version}
								<div class="border border-gray-200 rounded-lg p-3">
									<div class="text-sm font-medium text-gray-900 mb-2">
										<span class={`px-2 py-1 rounded text-xs font-medium ${getTypeColor(version.type)}`}>
											{getTypeLabel(version.type)}
										</span>
										<div class="text-xs text-gray-500 mt-1">{formatDate(version.timestamp)}</div>
										<div class="text-xs text-gray-500">{version.wordCount} words</div>
									</div>
									<div class="text-sm text-gray-700 max-h-64 overflow-y-auto whitespace-pre-wrap">
										{version.content}
									</div>
								</div>
							{/each}
						</div>

						<!-- Diff View -->
						<div class="border border-gray-200 rounded-lg p-3 bg-gray-50">
							<h5 class="text-sm font-medium text-gray-900 mb-2">Changes</h5>
							<div class="text-sm space-y-1 max-h-48 overflow-y-auto">
								{#each getHighlightedDiff(selectedVersions[0].content, selectedVersions[1].content) as diff}
									<span
										class={diff.isAdded
											? 'bg-green-100 text-green-900'
											: 'text-gray-700'}
									>
										{diff.text}&nbsp;
									</span>
								{/each}
							</div>
							<div class="text-xs text-gray-600 mt-3 pt-2 border-t border-gray-200">
								<span class="inline-block bg-green-100 text-green-900 px-2 py-1 rounded mr-2">Added</span>
								<span class="inline-block text-gray-700 px-2 py-1 rounded">Unchanged</span>
							</div>
						</div>
					{/if}
				</div>
			{/if}
		</div>
	{/if}
</div>
